channels:
- anaconda
- conda-forge
dependencies:
- python=3.6.8
- python=3.8.9
- pip:
  - pandas==1.4.3
  - azureml-defaults
  - joblib==0.17.0
  - scikit-learn==1.1.2
  - matplotlib == 3.5.2
  - numpy == 1.23.1
  - seaborn == 0.11.2
name: azureml_2d0fd20031db3baaed8684d5f08fe619